packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

variable "aws_access_key" {
  type    = string
  default = "${env("AWS_ACCESS_KEY_ID")}"
}

variable "aws_secret_key" {
  type    = string
  default = "${env("AWS_SECRET_ACCESS_KEY")}"
}

variable "region" {
  type    = string
  default = "ap-south-1"
}

data "amazon-ami" "autogenerated_1" {
  access_key = "${var.aws_access_key}"
  filters = {
    name                = "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "ap-south-1"
  secret_key  = "${var.aws_secret_key}"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  access_key    = "${var.aws_access_key}"
  ami_name      = "packer-linux-aws-demo-${local.timestamp}"
  instance_type = "t2.micro"
  region        = "ap-south-1"
  secret_key    = "${var.aws_secret_key}"
  source_ami    = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username  = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "file" {
    destination = "/home/ubuntu/"
    source      = "./welcomefile"
  }

  provisioner "file" {
    destination = "/home/ubuntu/"
    source      = "./index.html"
  }

  provisioner "file" {
    destination = "/home/ubuntu/"
    source      = "./styles.css"
  }

  provisioner "file" {
    destination = "/home/ubuntu/"
    source      = "./script.js"
  }

  provisioner "shell" {
    inline = ["ls -al /home/ubuntu", "cat /home/ubuntu/welcomefile", "sudo apt update", "sleep 10", "sudo apt -y install apache2", "sudo systemctl enable apache2.service", "sleep 5", "sudo mv /home/ubuntu/index.html /var/www/html/", "sudo mv /home/ubuntu/styles.css /var/www/html/", "sudo mv /home/ubuntu/script.js /var/www/html/"]
  }

  provisioner "shell" {
    script = "./setup.sh"
  }

}
